#!/usr/bin/env python3
"""check-index-drift.py (#281) — regenerate-and-diff guard for the committed index pages.

The aggregate `library/index.html` and the per-domain `library/{domain}/lessons/index.html`
are GENERATED by `generate_index_page.py`. A committed page can drift from what the generator
now emits (a stale artifact — the #281 problem: a page importing a component the generator no
longer produces), so regenerating silently changes it. This gate catches that.

Approach: for each page, SNAPSHOT the committed bytes, regenerate to the REAL path
(map_href is document-relative to the output's `../maps/` sibling, so a temp copy elsewhere
can't reproduce the committed hrefs — and cross-drive temp breaks os.path.relpath on
Windows), compare fresh-vs-snapshot in memory, then RESTORE the snapshot (non-destructive).

Comparing the pre-regen snapshot (not a post-regen git diff) is essential: an in-place regen
OVERWRITES a hand-edit before any git diff could see it, so a git-diff-after-overwrite guard
silently reverts stale fields instead of flagging them (caught by a negative test). The
snapshot compare catches BOTH stale artifacts (generator output changed) AND hand-edits to
generated fields.

Requires the generator to be idempotent (it is: counts re-bake from committed demo fixtures,
#279). Run in `mise run verify`. NOTE: this regenerates committed files — safe because the
generator is deterministic; a clean run leaves the tree byte-identical.
"""
from __future__ import annotations

# Windows consoles default to cp1252; force UTF-8 so ✓/→ glyphs don't crash (#265).
import sys as _sys
if hasattr(_sys.stdout, "reconfigure"):
    _sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(_sys.stderr, "reconfigure"):
    _sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
LIBRARY = PROJECT_ROOT / "library"
GENERATOR = PROJECT_ROOT / "tools" / "generate_index_page.py"


def _targets() -> list[tuple[Path, Path]]:
    """(scan-dir, committed output) pairs: the aggregate + each per-domain index page."""
    targets = [(LIBRARY, LIBRARY / "index.html")]
    for idx in sorted(LIBRARY.glob("*/lessons/index.html")):
        targets.append((idx.parent.parent, idx))  # scan the {domain}/ dir
    return targets


def main() -> int:
    if not GENERATOR.exists():
        print(f"✗ generator not found: {GENERATOR}", file=sys.stderr)
        return 2

    drifted: list[str] = []
    checked = 0
    for scan_dir, committed in _targets():
        rel = str(committed.relative_to(PROJECT_ROOT)).replace("\\", "/")
        if not committed.exists():
            print(f"  [skip] {rel} (not committed)")
            continue
        # Snapshot the committed bytes BEFORE regenerating. The generator writes to the REAL
        # path (map_href needs the ../maps sibling), so we must capture-then-restore rather
        # than regenerate-then-git-diff: an in-place regen OVERWRITES a hand-edit before any
        # diff can see it (the negative-test bug — a stale committed field gets silently
        # reverted, not flagged). Comparing the pre-regen snapshot against fresh output
        # catches BOTH stale artifacts (generator drift) AND hand-edits to generated fields.
        before = committed.read_text(encoding="utf-8")
        r = subprocess.run(
            [sys.executable, str(GENERATOR), "--scan-dir", str(scan_dir), "--output", str(committed)],
            capture_output=True, text=True,
        )
        fresh = committed.read_text(encoding="utf-8") if r.returncode == 0 else None
        # Restore the committed bytes so the guard is NON-DESTRUCTIVE regardless of outcome.
        committed.write_text(before, encoding="utf-8")
        if r.returncode != 0:
            print(f"✗ generator error for {rel}:\n{r.stderr}", file=sys.stderr)
            return 2
        checked += 1
        if fresh != before:
            drifted.append(rel)
            print(f"  [DRIFT] {rel} — committed page differs from generator output")
        else:
            print(f"  [ok] {rel}")

    if drifted:
        print(f"\n✗ {len(drifted)} index page(s) drifted from the generator "
              f"(regenerate + commit, do NOT hand-edit):", file=sys.stderr)
        for d in drifted:
            print(f"    {d}", file=sys.stderr)
        return 1
    print(f"\n✓ index pages in sync with the generator ({checked} checked)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
