#!/usr/bin/env python3
"""check-index-drift.py (#281) — regenerate-and-diff guard for the committed index pages.

The aggregate `library/index.html` and the per-domain `library/{domain}/lessons/index.html`
are GENERATED by `generate_index_page.py`. A committed page can drift from what the generator
now emits (a stale artifact — the #281 problem: a page importing a component the generator no
longer produces), so regenerating silently changes it. This gate catches that.

Approach: regenerate each page IN PLACE, then `git diff --exit-code`. In-place regeneration
is required because `map_href` is document-relative to the output file's REAL location (its
sibling `../maps/` dir) — a temp copy elsewhere can't reproduce the committed relative hrefs
(and cross-drive temp dirs break os.path.relpath on Windows). git is the before/after oracle.

- Clean (no drift): git shows no change; nothing to restore; exit 0.
- Drift: git diff is non-empty; exit 1 and LEAVE the regenerated files in the tree so the
  user can inspect + commit them (do NOT hand-edit; regenerate is the fix).

Requires the generator to be idempotent (it is: counts re-bake from committed demo fixtures,
#279). Run in `mise run verify`. NOTE: this regenerates committed files — safe because the
generator is deterministic; a clean run leaves the tree byte-identical.
"""
from __future__ import annotations

# Windows consoles default to cp1252; force UTF-8 so ✓/→ glyphs don't crash (#265).
import sys as _sys
if hasattr(_sys.stdout, "reconfigure"):
    _sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(_sys.stderr, "reconfigure"):
    _sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
LIBRARY = PROJECT_ROOT / "library"
GENERATOR = PROJECT_ROOT / "tools" / "generate_index_page.py"


def _targets() -> list[tuple[Path, Path]]:
    """(scan-dir, committed output) pairs: the aggregate + each per-domain index page."""
    targets = [(LIBRARY, LIBRARY / "index.html")]
    for idx in sorted(LIBRARY.glob("*/lessons/index.html")):
        targets.append((idx.parent.parent, idx))  # scan the {domain}/ dir
    return targets


def main() -> int:
    if not GENERATOR.exists():
        print(f"✗ generator not found: {GENERATOR}", file=sys.stderr)
        return 2

    regenerated: list[Path] = []
    for scan_dir, committed in _targets():
        if not committed.exists():
            print(f"  [skip] {committed.relative_to(PROJECT_ROOT)} (not committed)")
            continue
        r = subprocess.run(
            [sys.executable, str(GENERATOR), "--scan-dir", str(scan_dir), "--output", str(committed)],
            capture_output=True, text=True,
        )
        if r.returncode != 0:
            print(f"✗ generator error for {committed.relative_to(PROJECT_ROOT)}:\n{r.stderr}", file=sys.stderr)
            return 2
        regenerated.append(committed)

    # git diff over the regenerated set — non-empty = drift.
    rel_paths = [str(p.relative_to(PROJECT_ROOT)).replace("\\", "/") for p in regenerated]
    diff = subprocess.run(
        ["git", "diff", "--name-only", "--"] + rel_paths,
        cwd=str(PROJECT_ROOT), capture_output=True, text=True,
    )
    drifted = [ln for ln in diff.stdout.splitlines() if ln.strip()]

    if drifted:
        print(f"✗ {len(drifted)} index page(s) drifted from the generator "
              f"(regenerated in place — inspect + commit, do NOT hand-edit):", file=sys.stderr)
        for d in drifted:
            print(f"    {d}", file=sys.stderr)
        return 1
    print(f"✓ index pages in sync with the generator ({len(regenerated)} checked)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
