#!/usr/bin/env python3
"""Backfill the lesson-actions config script into existing lesson pages (#264).

Lesson pages load `page-shell.js`, which mounts LessonActions (the bottom bar with
"✓ Mark complete"). That component reads `data-domain` / `data-lesson-id` /
`data-map-page` / `data-topic-title` from a `script[data-domain]` to build the
`/api/map/{domain}/{slug}/status` endpoint. `render_lesson_page` now emits this script,
but pages generated by older templates lack it — so mark-complete POSTs to
`/api/map/null/...` and fails.

This injects the config script immediately before the `page-shell.js` tag. Idempotent
(skips if already present). The domain slug is read from EACH page's own breadcrumb
`*-map.html` href — NOT hardcoded per workspace, because a workspace can have several
maps (e.g. godot-gamedev has godot-gamedev / godot-toon-shaders / godot-mktoon /
blender-texture-prep), and a lesson belongs to whichever map its breadcrumb links to.

Usage:
    python tools/migrate-add-lesson-actions.py --workspace examples/oidc-rust
    python tools/migrate-add-lesson-actions.py --all              # every examples/* workspace
    python tools/migrate-add-lesson-actions.py --all --dry-run
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# Windows consoles default to cp1252; force UTF-8 so the ✓ glyph doesn't crash.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "tools"))
from lib.page_template import _esc

# The middle breadcrumb crumb links to the domain's map: <a href="{slug}-map.html">.
_MAP_HREF_RE = re.compile(r'href="([^"]*?)-map\.html"')
_H1_RE = re.compile(r"<h1[^>]*>(.+?)</h1>", re.DOTALL)
_PAGE_SHELL_RE = re.compile(r'\n?[ \t]*<script type="module" src="[^"]*page-shell\.js"></script>')


def _is_lesson_page(path: Path) -> bool:
    """Lesson CONTENT pages only — exclude maps, index, quiz, reference, review."""
    name = path.name
    rel = path.as_posix()
    if name == "index.html" or name.endswith("-map.html"):
        return False
    if "/quiz/" in rel or "/reference/" in rel or "/review/" in rel:
        return False
    return "/lessons/" in rel


def _domain_slug_from_breadcrumb(content: str) -> str | None:
    """The lesson's domain slug = the `*-map.html` href in its own breadcrumb nav.

    Takes the LAST match to skip a bare `index.html` and land on the domain crumb
    (the breadcrumb is: All Lessons › {domain}-map.html › Title).
    """
    matches = _MAP_HREF_RE.findall(content)
    return matches[-1] if matches else None


def _title(content: str) -> str:
    m = _H1_RE.search(content)
    if not m:
        return ""
    return re.sub(r"<[^>]+>", "", m.group(1)).strip()


def inject(path: Path) -> str | None:
    """Return modified content, or None to skip (already present / can't resolve)."""
    content = path.read_text(encoding="utf-8")

    if 'id="lesson-actions-config"' in content or "data-domain" in content:
        return None  # idempotent

    slug = _domain_slug_from_breadcrumb(content)
    if not slug:
        return None  # no domain crumb — can't wire it
    title = _title(content)
    lesson_id = path.stem

    attrs = " ".join([
        f'data-domain="{_esc(slug)}"',
        f'data-lesson-id="{_esc(lesson_id)}"',
        f'data-map-page="{_esc(slug)}-map.html"',
        f'data-topic-title="{_esc(title)}"',
    ])
    tag = f'<script type="application/json" id="lesson-actions-config" {attrs}></script>'

    # Insert immediately before the page-shell.js script tag.
    m = _PAGE_SHELL_RE.search(content)
    if not m:
        return None
    return content[:m.start()] + "\n" + tag + content[m.start():]


def _workspaces(args: list[str]) -> list[Path]:
    if "--all" in args:
        return sorted(p for p in (PROJECT_ROOT / "examples").iterdir() if p.is_dir())
    if "--workspace" in args:
        i = args.index("--workspace")
        if i + 1 < len(args):
            ws = Path(args[i + 1])
            return [ws if ws.is_absolute() else PROJECT_ROOT / ws]
    return [PROJECT_ROOT / "workspace"]


def main() -> int:
    args = sys.argv[1:]
    dry_run = "--dry-run" in args
    updated = skipped = 0
    for ws in _workspaces(args):
        lessons = ws / "lessons"
        if not lessons.exists():
            continue
        for f in sorted(lessons.rglob("*.html")):
            if not _is_lesson_page(f):
                continue
            result = inject(f)
            if result is None:
                skipped += 1
                continue
            if dry_run:
                print(f"  [dry-run] {f.relative_to(PROJECT_ROOT)}")
            else:
                f.write_text(result, encoding="utf-8")
                print(f"  ✓ {f.relative_to(PROJECT_ROOT)}")
            updated += 1
    action = "would update" if dry_run else "updated"
    print(f"\n{action} {updated} lesson page(s), skipped {skipped}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
